/**:
    ros__parameters:
      app_name: "M30"
      app_id: "143537"
      app_key: "bcf5b8d498ce256aee10c32613909d1"
      app_license: "vb1J8Md0vbCEBjXRokWyGOrEEIGyJcgyUIY4xFe2DsE8g7nQABFqPXIIcRFtrl8MmVYlVgGN3GOH3ediIUOy2/QikxHaID4COsct5IjexSUulsUfjF26qITUj2xw8gzsnh2aqbRD78bqgp1BfHz5V6/WOK/nL1dfyEmHNZME/SfCA0Cht5b9aLqM/HMX9CQCLCwl9Q79QCI3JwtiDLMOIUzlGw61gWKORjYUyIp8xdr7XcBQreWjU/5B63yDO5KVFFkupU6yyuMlPJyiO2+104Fl6clrLU/jC35Ih4Tz3aJ7MIa6f5S1rvb9XU5YHLbQ8Zb0W14v4TLhIQpng9lRIg=="
      developer_account: "umesh@farmx.ag"
      baudrate: "921600"

      num_of_initialization_retries: 3

      tf_frame_prefix: ""
      imu_frame: "psdk_imu_link"
      body_frame: "psdk_base_link"
      map_frame: "psdk_map_enu"
      gimbal_base_frame: "psdk_gimbal_base_link"
      gimbal_frame: "psdk_gimbal_link"
      camera_frame: "psdk_camera_link"
      perception_camera_frame: "psdk_perception_camera_link"
      publish_transforms: true

      file_path: "/logs/media/"

      # Mandatory modules to be initialized. Mark with a true those which you
      # consider mandatory for your application, false otherwise. Be aware that
      # some modules might have inter-dependencies. Non mandatory modules will
      # still be initialized but if case of failure, the node will continue to run.
      mandatory_modules:
        telemetry: true
        flight_control: true
        camera: true
        gimbal: true
        liveview: true
        hms: true
        perception: true
        waypoint_v2: false

      data_frequency: # Options are: 1, 5, 10, 50, 100, 200, 400 Hz
        imu: 100
        attitude: 100
        acceleration: 50
        velocity: 50
        angular_velocity: 100
        position: 50
        altitude: 50
        gps_fused_position: 10
        gps_data: 5
        rtk_data: 5
        magnetometer: 50
        rc_channels_data: 1
        gimbal_data: 1
        flight_status: 1
        battery_level: 1
        control_information: 1
        esc_data_frequency: 1
